language: cpp

os:
  - linux

branches:
  only:
  - develop

compiler:
  - gcc

env:
  - CONFIGURATION="Release"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-8

install:
  - sudo apt-get install libboost-all-dev libgtest-dev -y
  - cd /usr/src/gtest
  - sudo env "PATH=$PATH" cmake .
  - sudo env "PATH=$PATH" cmake --build .
  - pwd
  
before_script:
  - export CXX="g++-8"

script:
  - cd $TRAVIS_BUILD_DIR
  - pwd
  - mkdir build
  - cd build
  - pwd
  - cmake ..
  - cmake --build . --config $CONFIGURATION
  - ctest -C $CONFIGURATION --output-on-failure
