language: cpp

os:
  - linux

branches:
  only:
  - develop

compiler:
  - gcc

env:
  - CONFIGURATION="Release"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-8

install:
  - sudo apt-get install libboost-all-dev libgtest-dev -y

before_script:
  - export CXX="g++-8"
  - cd /usr/src/gtest
  - sudo cmake .
  - sudo cmake --build . --target install

script:
  - mkdir ./build
  - cd ./build
  - cmake ..
  - cmake --build . --config $CONFIGURATION
  - ctest -C $CONFIGURATION --output-on-failure
