language: cpp

os:
  - linux

compiler:
  - gcc

env:
  - PLATFORM=x86 CONFIGURATION=Release TARGET_CPU=-m32
  - PLATFORM=x64 CONFIGURATION=Release TARGET_CPU=-m64

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-8

install:
  - sudo apt-get install libboost-all-dev -y

before_script:
  - export CXX="g++-8"
  - export CPPLAGS=$TARGET_CPU

script:
  - mkdir ./build
  - cd ./build
  - cmake .. #-DTARGET_CPU=$TARGET_CPU
  - cmake --build . --config $CONFIGURATION
#- cmake --build . --target test

#branches:
#  only:
#  - master
#  - "/^v\\d+\\./"


